version: '3.8'

services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - my_network
  

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sippyyy/social-media-fast-api
    restart: unless-stopped
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      # DEBUG: 1
      # DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
      # DATABASE_HOST: "db"
      # DATABASE_PORT: 5432
      # PORT: 8000
      # GUNICORN_WORKERS: 4
      # DATABASE_HOSTNAME: db
      # DATABASE_PASSWORD: postgres
      # DATABASE_NAME : postgres
      # DATABASE_USERNAME : postgres 
      # SECRET_KEY : 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      # ALGORITHM : HS256
      # ACCESS_TOKEN_EXPIRE_MINUTES : 30 

      DATABASE_HOSTNAME : ${DATABASE_HOSTNAME}
      DATABASE_PORT : ${DATABASE_PORT}
      DATABASE_PASSWORD : ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    networks:
      - my_network  



volumes:
  pgdata:
  static_volume:

networks:
  my_network:
