version: '3.8'

services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nguyenthuy209
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - my_network
  

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # DEBUG: 1
      # DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
      # DATABASE_HOST: "db"
      # DATABASE_PORT: 5432
      # PORT: 8000
      # GUNICORN_WORKERS: 4
      # DATABASE_HOSTNAME: db
      # DATABASE_PASSWORD: postgres
      # DATABASE_NAME : postgres
      # DATABASE_USERNAME : postgres 
      # SECRET_KEY : 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      # ALGORITHM : HS256
      # ACCESS_TOKEN_EXPIRE_MINUTES : 30 

      DATABASE_HOSTNAME : db
      DATABASE_PORT : 5432
      DATABASE_PASSWORD : nguyenthuy209
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    networks:
      - my_network  



volumes:
  pgdata:
  static_volume:

networks:
  my_network:
